export const videos = [
    { id: "video1", title: "Introduction", url: "https://www.youtube.com/watch?v=0W6qz0-aDaM&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=1" },
    { id: "video2", title: "Selectors", url: "https://www.youtube.com/watch?v=QgxkYbGr2II&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=2" },
    { id: "video3", title: "Colors", url: "https://www.youtube.com/watch?v=Ddc-IIrIot0&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=3&pp=iAQB" },
    { id: "video4", title: "Units & Sizes", url: "https://www.youtube.com/watch?v=_ybQREu-NU0&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=4&pp=iAQB" },
    { id: "video5", title: "Box Model", url: "https://www.youtube.com/watch?v=L9khsrjMwKw&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=5&pp=iAQB" },
    { id: "video6", title: "Typography", url: "https://www.youtube.com/watch?v=klXyJWlIzuY&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=6&pp=iAQB" },
    { id: "video7", title: "Hypertext", url: "https://www.youtube.com/watch?v=sORF-Awir70&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=7&pp=iAQB" },
    { id: "video8", title: "List Styles", url: "https://www.youtube.com/watch?v=jcThx0U066w&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=8&pp=iAQB" },
    { id: "video9", title: "Mini-Project", url: "https://www.youtube.com/watch?v=rwTs9NR3Du8&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=9&pp=iAQB" },
    { id: "video10", title: "Display Property", url: "https://www.youtube.com/watch?v=naTAFo2Gyus&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=10&pp=iAQB" },
    { id: "video11", title: "Floats and Clears", url: "https://www.youtube.com/watch?v=QkvFxXqElQ4&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=11&pp=iAQB" },
    { id: "video12", title: "Columns", url: "https://www.youtube.com/watch?v=f0A7moLkAL0&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=12&pp=iAQB" },
    { id: "video13", title: "Position Property", url: "https://www.youtube.com/watch?v=zqg4A6g9GfA&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=13&pp=iAQB" },
    { id: "video14", title: "Flexbox", url: "https://www.youtube.com/watch?v=B8BFVzbKmPI&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=14&pp=iAQB" },
    { id: "video15", title: "Grid", url: "https://www.youtube.com/watch?v=EaWj2AWI5Es&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=15&pp=iAQB" },
    { id: "video16", title: "Background Images and Responsive Image Properties", url: "https://www.youtube.com/watch?v=cLyzBfXI0I0&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=16&pp=iAQB" },
    { id: "video17", title: "Media Queries & Responsive Web Design", url: "https://www.youtube.com/watch?v=69IbzTWg5PM&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=17&pp=iAQB" },
    { id: "video18", title: "Responsive Card Design | Mini-Project", url: "https://www.youtube.com/watch?v=mpYtrgB3b6o&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=18&pp=iAQB" },
    { id: "video19", title: "Pseudo-Classes vs Pseudo-Elements", url: "https://www.youtube.com/watch?v=GNmz5dYjdcQ&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=19&pp=iAQB" },
    { id: "video20", title: "Custom Variables & Dark Mode", url: "https://www.youtube.com/watch?v=K_M7D0PfOFM&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=20&pp=iAQB" },
    { id: "video21", title: "Functions | min, max, clamp, minmax, calc, attr", url: "https://www.youtube.com/watch?v=qWnIadj5b30&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=21&pp=iAQB" },
    { id: "video22", title: "Animated Responsive Navbar", url: "https://www.youtube.com/watch?v=PN5OC1mZlfY&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=22&pp=iAQB" },
    { id: "video23", title: "How to Organize CSS", url: "https://www.youtube.com/watch?v=MNPdifWAAa4&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=23&pp=iAQB" },
    { id: "video24", title: "Complete Project", url: "https://www.youtube.com/watch?v=cMN2Odm5ieA&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=24&pp=iAQB" },
    { id: "video25", title: "HTML CSS Animations Reverse Mobile Menu Navbar", url: "https://www.youtube.com/watch?v=VzkWH7mJpe8&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=26&pp=iAQB" },
    { id: "video26", title: "How to use the CSS :has selector", url: "https://www.youtube.com/watch?v=XdtZWVK3y_Q&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=27&pp=iAQB" },
    { id: "video27", title: "Why Flexbox?", url: "https://www.youtube.com/watch?v=e9Fx2hRT-UQ&list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit&index=28&pp=iAQB" },
];

console.log("videos geladen");